### ISSUE TITLE
inputTextstring and input2Textstring

### ISSUE THREAD

**Issue by John-J-Russell** [cesar-avalos3/AndroidChat#1]
These are wonky. There was and input2Textstring in ChatActivity before I removed it (I thought it was a typo), however recent evidence from Alec suggests it wasn't.
The difficulties arise in that nowhere else does "input2Textstring" exist.
Valve, please fix.

**Comment by cesar-avalos3** [comment]
Pls Volvo gieb fix ༼ つ ◕_◕ ༽つ
